import { MemberRole } from '@/types';

export const PERMISSIONS = {
  // Platform Superadmin
  MANAGE_PLATFORM_ALL: 'manage_platform_all',
  
  // Company & Settings
  MANAGE_COMPANY_SETTINGS: 'manage_company_settings',
  VIEW_COMPANY_SETTINGS: 'view_company_settings',
  MANAGE_BILLING: 'manage_billing',
  VIEW_BILLING: 'view_billing',
  MANAGE_TEAM: 'manage_team',
  INVITE_MEMBERS: 'invite_members',

  // Leads
  VIEW_ALL_LEADS: 'view_all_leads',
  VIEW_ASSIGNED_LEADS: 'view_assigned_leads',
  CREATE_LEAD: 'create_lead',
  EDIT_LEAD: 'edit_lead',
  REASSIGN_LEAD: 'reassign_lead',
  MERGE_DUPLICATE_LEADS: 'merge_duplicate_leads',
  IMPORT_LEADS: 'import_leads',
  EXPORT_LEADS: 'export_leads',

  // Projects & Inventory
  MANAGE_PROJECTS: 'manage_projects',
  VIEW_PROJECTS: 'view_projects',
  HOLD_UNIT: 'hold_unit',
  BLOCK_UNIT: 'block_unit',

  // Tasks & Visits
  MANAGE_TASKS: 'manage_tasks',
  MANAGE_SITE_VISITS: 'manage_site_visits',

  // Bookings & Payments
  CREATE_BOOKING: 'create_booking',
  APPROVE_DISCOUNT: 'approve_discount',
  CANCEL_BOOKING: 'cancel_booking',
  RECORD_PAYMENT: 'record_payment',
  RECONCILE_PAYMENT: 'reconcile_payment',
  VIEW_FINANCIALS: 'view_financials',

  // Channel Partners
  MANAGE_CHANNEL_PARTNERS: 'manage_channel_partners',
  APPROVE_COMMISSION: 'approve_commission',
  PAY_COMMISSION: 'pay_commission',

  // Integrations & Reports
  MANAGE_INTEGRATIONS: 'manage_integrations',
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<MemberRole, Permission[]> = {
  company_owner: [
    PERMISSIONS.MANAGE_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_COMPANY_SETTINGS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.INVITE_MEMBERS,
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.VIEW_ASSIGNED_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.REASSIGN_LEAD,
    PERMISSIONS.MERGE_DUPLICATE_LEADS,
    PERMISSIONS.IMPORT_LEADS,
    PERMISSIONS.EXPORT_LEADS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.HOLD_UNIT,
    PERMISSIONS.BLOCK_UNIT,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_SITE_VISITS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.APPROVE_DISCOUNT,
    PERMISSIONS.CANCEL_BOOKING,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.RECONCILE_PAYMENT,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_CHANNEL_PARTNERS,
    PERMISSIONS.APPROVE_COMMISSION,
    PERMISSIONS.PAY_COMMISSION,
    PERMISSIONS.MANAGE_INTEGRATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  company_admin: [
    PERMISSIONS.MANAGE_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.INVITE_MEMBERS,
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.VIEW_ASSIGNED_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.REASSIGN_LEAD,
    PERMISSIONS.MERGE_DUPLICATE_LEADS,
    PERMISSIONS.IMPORT_LEADS,
    PERMISSIONS.EXPORT_LEADS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.HOLD_UNIT,
    PERMISSIONS.BLOCK_UNIT,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_SITE_VISITS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.APPROVE_DISCOUNT,
    PERMISSIONS.CANCEL_BOOKING,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.RECONCILE_PAYMENT,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_CHANNEL_PARTNERS,
    PERMISSIONS.APPROVE_COMMISSION,
    PERMISSIONS.MANAGE_INTEGRATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  sales_manager: [
    PERMISSIONS.VIEW_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.VIEW_ASSIGNED_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.REASSIGN_LEAD,
    PERMISSIONS.MERGE_DUPLICATE_LEADS,
    PERMISSIONS.EXPORT_LEADS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.HOLD_UNIT,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_SITE_VISITS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.MANAGE_CHANNEL_PARTNERS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  sales_executive: [
    PERMISSIONS.VIEW_ASSIGNED_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.HOLD_UNIT,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_SITE_VISITS,
    PERMISSIONS.CREATE_BOOKING,
  ],
  telecaller: [
    PERMISSIONS.VIEW_ASSIGNED_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.MANAGE_TASKS,
  ],
  accounts: [
    PERMISSIONS.VIEW_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.RECONCILE_PAYMENT,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.PAY_COMMISSION,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  viewer: [
    PERMISSIONS.VIEW_COMPANY_SETTINGS,
    PERMISSIONS.VIEW_ALL_LEADS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_REPORTS,
  ],
};

export function hasPermission(role: MemberRole | undefined, permission: Permission): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function canAccessLead(role: MemberRole, assignedMemberId: string | undefined, currentMemberId: string): boolean {
  if (['company_owner', 'company_admin', 'sales_manager', 'viewer'].includes(role)) {
    return true;
  }
  return assignedMemberId === currentMemberId;
}

export const ROLE_LABELS: Record<MemberRole, string> = {
  company_owner: 'Company Owner',
  company_admin: 'Company Admin',
  sales_manager: 'Sales Manager',
  sales_executive: 'Sales Executive / Agent',
  telecaller: 'Telecaller',
  accounts: 'Accounts & Finance',
  viewer: 'Viewer (Read Only)',
};
